version: '3.8'
services:
  backend:
    build:
      context: ./server   # Contexte où se trouve le Dockerfile
    ports:
      - "80:8000"
    environment:
      - DB_HOST=db         # Nom du service de la DB dans Docker Compose
      - DB_USER=postgres
      - DB_PASSWORD=Walksafe
      - DB_NAME=school
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Walksafe
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
