version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webapp-network

  backend:
    build:
      context: ./server
    container_name: webapp-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: school
    ports:
      - "80:8000"
    depends_on:
      - postgres
    networks:
      - webapp-network

  frontend:
    build:
      context: ./client
    container_name: webapp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - webapp-network

volumes:
  postgres-data:

networks:
  webapp-network:
