apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # "postgres" en Base64
  postgres-password: V2Fsa3NhZmU=  # "Walksafe" en Base64
  postgres-database: c2Nob29s  # "school" en Base64
