apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-service
  namespace: default
spec:
  selector:
    app: webapp-backend
  ports:
  - protocol: TCP
    port: 80              # Port exposé à l'extérieur
    targetPort: 8000      # Port interne du backend
    nodePort: 30080
  type: NodePort           # Expose le backend à l'extérieur du cluster
