apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
  namespace: default
spec:
  selector:
    app: webapp-frontend
  ports:
  - protocol: TCP
    port: 80                      # Port exposé pour l'application React
    targetPort: 3000                # Port où le frontend React écoute
    nodePort: 30001
  type: NodePort               
